# Generated by Django 4.2.7 on 2026-05-13 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_block_onevaschargingtransaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconfig',
            name='withdrawal_min_points',
            field=models.PositiveIntegerField(default=1000, help_text='Minimum points required to withdraw'),
        ),
    ]
