# Generated by Django 4.2.7 on 2026-05-14 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_block_onevaschargingtransaction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='shares',
            field=models.IntegerField(default=0),
        ),
    ]
