# Generated by Django 4.2.7 on 2026-05-13 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0071_alter_walletconfig_withdrawal_min_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('domain', models.CharField(choices=[('identity', 'Identity'), ('content', 'Content'), ('campaign', 'Campaign'), ('voting', 'Voting'), ('payment', 'Payment'), ('subscription', 'Subscription'), ('wallet', 'Wallet'), ('gift', 'Gift'), ('support', 'Support'), ('gamification', 'Gamification'), ('messaging', 'Messaging'), ('admin', 'Admin'), ('audit', 'Audit')], help_text='Domain/category of the permission', max_length=20)),
                ('name', models.CharField(help_text='Human-readable permission name', max_length=100)),
                ('description', models.TextField(help_text='Detailed description of what this permission allows')),
                ('is_active', models.BooleanField(default=True, help_text='Is this permission currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permissions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Permission',
                'verbose_name_plural': 'Permissions',
                'ordering': ['domain', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(help_text='Description of what this role can do')),
                ('type', models.CharField(choices=[('platform_user', 'Platform User'), ('internal_operator', 'Internal Operator')], help_text='Type of role: platform user or internal operator', max_length=20)),
                ('surfaces', models.JSONField(default=list, help_text='List of surfaces where this role is applicable')),
                ('is_default', models.BooleanField(default=False, help_text='Is this the default role for new users?')),
                ('is_active', models.BooleanField(default=True, help_text='Is this role currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='roles_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['type', 'name'],
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Is this user an internal operator (admin staff)?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(blank=True, help_text='User role for RBAC', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='api.role'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('full', 'Full Access'), ('read_only', 'Read-Only Access'), ('none', 'No Access')], default='none', help_text='Level of access for this permission', max_length=10)),
                ('conditions', models.JSONField(blank=True, default=dict, help_text='Conditional access rules (e.g., if subscribed)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permissions_created', to=settings.AUTH_USER_MODEL)),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='api.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.role')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_permissions_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Role Permission',
                'verbose_name_plural': 'Role Permissions',
                'ordering': ['role', 'permission'],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('role_assign', 'Role Assignment'), ('role_revoke', 'Role Revocation'), ('permission_grant', 'Permission Granted'), ('permission_revoke', 'Permission Revoked'), ('user_suspend', 'User Suspended'), ('user_unsuspend', 'User Unsuspended'), ('config_change', 'Platform Configuration Changed'), ('role_create', 'Role Created'), ('role_update', 'Role Updated'), ('role_delete', 'Role Deleted'), ('permission_create', 'Permission Created'), ('permission_update', 'Permission Updated'), ('permission_delete', 'Permission Deleted'), ('role_permission_update', 'Role Permission Updated')], help_text='Type of action performed', max_length=50)),
                ('target_type', models.CharField(help_text='Type of target (user, role, permission, etc.)', max_length=50)),
                ('target_id', models.CharField(help_text='ID of the target object', max_length=100)),
                ('target_name', models.CharField(blank=True, help_text='Human-readable name of the target', max_length=200)),
                ('old_value', models.JSONField(blank=True, help_text='Previous value before change', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New value after change', null=True)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the actor')),
                ('user_agent', models.TextField(help_text='User agent string of the actor')),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the action occurred')),
                ('actor', models.ForeignKey(help_text='User who performed the action', on_delete=django.db.models.deletion.PROTECT, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['actor'], name='api_auditlo_actor_i_662f04_idx'), models.Index(fields=['action'], name='api_auditlo_action_0a1743_idx'), models.Index(fields=['timestamp'], name='api_auditlo_timesta_da87a7_idx'), models.Index(fields=['target_type', 'target_id'], name='api_auditlo_target__da2d13_idx')],
            },
        ),
    ]
