# Generated by Django 4.2.11 on 2026-08-17 21:31
#
# Only the directdebitmandate.status field change is intentional here (adds
# the 'activating'/'cancelling' transient statuses used by the mandate
# activate/cancel race-condition fix in api/views/direct_debit.py).
# makemigrations also detected an unrelated, pre-existing drift on
# message.media (a machine-specific absolute FileSystemStorage path) --
# left out of this migration since it's unrelated to this change and
# environment-specific, not a real intended schema change.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0087_moderationaction_undone_moderationaction_undone_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directdebitmandate',
            name='status',
            field=models.CharField(choices=[('pending_created', 'Pending Creation'), ('pending_active', 'Pending Activation'), ('activating', 'Activation In Progress'), ('active', 'Active'), ('cancelling', 'Cancellation In Progress'), ('cancelled', 'Cancelled'), ('expired', 'Expired'), ('failed', 'Failed')], default='pending_created', max_length=20),
        ),
    ]
