# Generated by Django 4.2.11 on 2026-08-20 08:26

from django.db import migrations, models


def backfill_telebirr_bucket(apps, schema_editor):
    """
    Before this migration, every purchased coin was, by definition, bought
    via Telebirr -- the airtime purchase path did not exist yet. Move each
    user's existing purchased_balance/total_purchased into the new
    telebirr_purchased_balance/total_telebirr_purchased buckets so existing
    balances are preserved exactly (airtime_purchased_balance stays 0 for
    everyone, which is correct: no coin was ever bought that way before now).
    """
    UserCoinBalance = apps.get_model('api', 'UserCoinBalance')
    UserCoinBalance.objects.update(
        telebirr_purchased_balance=models.F('purchased_balance'),
        total_telebirr_purchased=models.F('total_purchased'),
    )


def noop_reverse(apps, schema_editor):
    # Nothing to reverse: purchased_balance/total_purchased were never
    # touched by the forward migration, only read from.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0090_directdebitmandate_debit_conversation_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinbalance',
            name='airtime_purchased_balance',
            field=models.PositiveIntegerField(default=0, help_text='Bought via Onevas airtime. Cannot be gifted.'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='telebirr_purchased_balance',
            field=models.PositiveIntegerField(default=0, help_text='Bought via Telebirr. Full use including gifting.'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='total_airtime_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime coins bought via Onevas airtime'),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='total_telebirr_purchased',
            field=models.PositiveIntegerField(default=0, help_text='Lifetime coins bought via Telebirr'),
        ),
        migrations.AlterField(
            model_name='usercoinbalance',
            name='purchased_balance',
            field=models.PositiveIntegerField(default=0, help_text='Total purchased coins (Telebirr + airtime).'),
        ),
        migrations.RunPython(backfill_telebirr_bucket, noop_reverse),
    ]
