# Generated by Django 4.2.11 on 2026-08-20 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0092_alter_message_media_consenthistory_userconsent'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawalrequest',
            name='b2c_transaction_id',
            field=models.UUIDField(blank=True, help_text='Linked B2CPaymentTransaction ID', null=True),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='conversation_id',
            field=models.CharField(blank=True, help_text='B2C conversation ID from Telebirr', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='originator_conversation_id',
            field=models.CharField(blank=True, help_text='B2C originator conversation ID', max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawalrequest',
            name='telebirr_transaction_id',
            field=models.CharField(blank=True, help_text='Telebirr transaction ID', max_length=100),
        ),
        migrations.AddIndex(
            model_name='withdrawalrequest',
            index=models.Index(fields=['originator_conversation_id'], name='api_withdra_origina_5dd7ae_idx'),
        ),
    ]
