# Generated by Django 4.2.11 on 2026-08-20 18:48

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0093_withdrawalrequest_b2c_transaction_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CRMGiftAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('award', 'Award Package'), ('retry', 'Retry Failed'), ('cancel', 'Cancel'), ('manual', 'Manual Override')], max_length=20)),
                ('details', models.TextField(blank=True, help_text='Additional details about the action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMGiftPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Package name (e.g., '1GB Data Package')", max_length=200)),
                ('offering_id', models.CharField(help_text='CRM OfferingId from Ethio Telecom', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Package description')),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Amount in ETB to charge for this package', max_digits=10)),
                ('min_level', models.IntegerField(default=1, help_text='Minimum user level required')),
                ('min_coins', models.IntegerField(default=0, help_text='Minimum coins required to claim')),
                ('trigger_condition', models.CharField(choices=[('campaign_win', 'Campaign Win'), ('contest_win', 'Contest Win'), ('leaderboard_top', 'Leaderboard Top Position'), ('manual', 'Manual Award')], default='manual', help_text='When this package is awarded', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this package is available')),
                ('max_awards_per_user', models.IntegerField(default=1, help_text='Maximum times a user can receive this package (0 = unlimited)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='WinnerGiftPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_type', models.CharField(choices=[('daily', 'Daily Winner'), ('weekly', 'Weekly Winner'), ('monthly', 'Monthly Winner'), ('grand', 'Grand Winner')], max_length=20, unique=True)),
                ('gift_type', models.CharField(choices=[('data', 'Data Gift (MB)'), ('cash', 'Cash Gift (ETB)')], max_length=20)),
                ('payment_method', models.CharField(choices=[('crm', 'CRM (Data Gift)'), ('telebirr_b2c', 'Telebirr B2C (Cash Gift)')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount in ETB or MB', max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Winner Gift Package',
                'verbose_name_plural': 'Winner Gift Packages',
            },
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='daily_win_limit_per_month',
            field=models.IntegerField(default=1, help_text='Max daily wins per month per user'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='grand_win_limit_per_campaign',
            field=models.IntegerField(default=1, help_text='Max grand wins per campaign per user'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='monthly_win_limit_per_period',
            field=models.IntegerField(default=1, help_text='Max monthly wins per campaign period per user'),
        ),
        migrations.AddField(
            model_name='campaignscoringconfig',
            name='weekly_win_limit_per_month',
            field=models.IntegerField(default=1, help_text='Max weekly wins per month per user'),
        ),
        migrations.CreateModel(
            name='WinnerGiftTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('winner_type', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=20)),
                ('receiver_msisdn', models.CharField(blank=True, max_length=20)),
                ('originator_conversation_id', models.CharField(blank=True, max_length=100)),
                ('conversation_id', models.CharField(blank=True, max_length=100)),
                ('telebirr_transaction_id', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('skipped', 'Skipped (Not Telebirr User)')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('gift_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.winnergiftpackage')),
                ('winner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Winner Gift Transaction',
                'verbose_name_plural': 'Winner Gift Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WinnerFrequencyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('grand', 'Grand')], max_length=20)),
                ('won_at', models.DateTimeField(auto_now_add=True)),
                ('period_start', models.DateTimeField(help_text='Start of the period this win belongs to')),
                ('period_end', models.DateTimeField(help_text='End of the period this win belongs to')),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='winner_frequency_records', to='api.campaign')),
                ('selection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frequency_records', to='api.winnerselection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winner_frequency_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-won_at'],
            },
        ),
        migrations.CreateModel(
            name='CRMGiftTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Phone number sent to CRM', max_length=20)),
                ('offering_id', models.CharField(help_text='CRM OfferingId used', max_length=50)),
                ('transaction_id', models.CharField(help_text='CRM TransactionId', max_length=50, unique=True)),
                ('charge_amount', models.DecimalField(decimal_places=2, help_text='Amount charged in ETB', max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('timeout', 'Timeout')], default='pending', max_length=20)),
                ('response_message', models.TextField(blank=True, help_text='CRM response message')),
                ('response_code', models.CharField(blank=True, help_text='CRM RetCode', max_length=10)),
                ('trigger_source', models.CharField(blank=True, help_text="What triggered this gift (e.g., 'campaign_123', 'manual_admin')", max_length=50)),
                ('campaign_id', models.IntegerField(blank=True, help_text='Related campaign ID if applicable', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When the CRM request completed', null=True)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='api.crmgiftpackage')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crm_gifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='crmgiftpackage',
            index=models.Index(fields=['offering_id'], name='api_crmgift_offerin_b5a0c7_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftpackage',
            index=models.Index(fields=['is_active'], name='api_crmgift_is_acti_4d66f6_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftpackage',
            index=models.Index(fields=['trigger_condition'], name='api_crmgift_trigger_6369ac_idx'),
        ),
        migrations.AddField(
            model_name='crmgiftauditlog',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crm_audit_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='crmgiftauditlog',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.crmgifttransaction'),
        ),
        migrations.AddIndex(
            model_name='winnergifttransaction',
            index=models.Index(fields=['winner', '-created_at'], name='api_winnerg_winner__f4bbb6_idx'),
        ),
        migrations.AddIndex(
            model_name='winnergifttransaction',
            index=models.Index(fields=['winner_type', '-created_at'], name='api_winnerg_winner__96c716_idx'),
        ),
        migrations.AddIndex(
            model_name='winnergifttransaction',
            index=models.Index(fields=['status'], name='api_winnerg_status_275e8c_idx'),
        ),
        migrations.AddIndex(
            model_name='winnergifttransaction',
            index=models.Index(fields=['originator_conversation_id'], name='api_winnerg_origina_0b44cd_idx'),
        ),
        migrations.AddIndex(
            model_name='winnerfrequencyrecord',
            index=models.Index(fields=['user', 'winner_type', '-won_at'], name='api_winnerf_user_id_531275_idx'),
        ),
        migrations.AddIndex(
            model_name='winnerfrequencyrecord',
            index=models.Index(fields=['winner_type', 'period_start', 'period_end'], name='api_winnerf_winner__0fddd1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='winnerfrequencyrecord',
            unique_together={('user', 'winner_type', 'period_start')},
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['user', '-created_at'], name='api_crmgift_user_id_5d67cb_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['transaction_id'], name='api_crmgift_transac_af2995_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['status'], name='api_crmgift_status_dea0a6_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['phone_number'], name='api_crmgift_phone_n_b16637_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgifttransaction',
            index=models.Index(fields=['offering_id'], name='api_crmgift_offerin_e5d718_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftauditlog',
            index=models.Index(fields=['transaction', '-created_at'], name='api_crmgift_transac_35066e_idx'),
        ),
        migrations.AddIndex(
            model_name='crmgiftauditlog',
            index=models.Index(fields=['action'], name='api_crmgift_action_3c2fb7_idx'),
        ),
    ]
