# Generated by Django 4.2.11 on 2026-08-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0097_alter_message_media_draft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemlog',
            name='log_type',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical'), ('security', 'Security'), ('admin_action', 'Admin Action')], max_length=20),
        ),
    ]
