# Generated by Django 4.2.11 on 2026-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0098_alter_message_media_alter_systemlog_log_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('GRANT', 'Grant'), ('REVOKE', 'Revoke')], max_length=10)),
                ('target_user', models.CharField(max_length=150)),
                ('target_user_id', models.IntegerField()),
                ('performed_by', models.CharField(max_length=150)),
                ('performed_by_id', models.IntegerField()),
                ('details', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Privilege Audit Log',
                'verbose_name_plural': 'Privilege Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='api_privile_timesta_7a71e3_idx'), models.Index(fields=['target_user_id'], name='api_privile_target__903c4a_idx'), models.Index(fields=['performed_by_id'], name='api_privile_perform_29f92a_idx')],
            },
        ),
    ]
