# Generated by Django 4.2.11 on 2026-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0099_alter_message_media_privilegeauditlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('telebirr', 'Telebirr'), ('telebirr_ussd', 'Telebirr USSD Push'), ('airtime', 'Airtime'), ('coins', 'Coins')], max_length=20),
        ),
    ]
