# Generated by Django 4.2.11 on 2026-08-21 17:57

"""Stabilise Message.media storage so migrations stop being machine-dependent.

Message.media previously received a FileSystemStorage *instance*. Django
serializes an instance by its constructor arguments, so every migration that
touched the field baked in that machine's absolute settings.MEDIA_ROOT. The
repository still contains three different developers' paths as a result, and
`makemigrations --check` -- the blocking django-checks CI gate -- could never
pass, because a CI runner's path matches none of them.

api/models/messaging.py now passes a callable instead, which Django serializes
by reference. This migration records that one-time change.

It is schema-neutral: `storage` is a Django-level attribute of FileField, not
a database column property, so this AlterField emits no DDL and touches no
rows. Existing media paths stored in the column are unaffected, and the
storage still resolves to settings.MEDIA_ROOT/MEDIA_URL exactly as before.
"""

import api.models.messaging
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0100_alter_cointransaction_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='media',
            field=models.FileField(blank=True, null=True, storage=api.models.messaging.message_media_storage, upload_to='messages/%Y/%m/'),
        ),
    ]
