# Generated by Django

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0102_timwe_integration'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='timwechargetransaction',
            new_name='api_timwech_status_093182_idx',
            old_name='api_timwech_status_6d2b84_idx',
        ),
        migrations.RenameIndex(
            model_name='timwechargetransaction',
            new_name='api_timwech_msisdn_fcf14c_idx',
            old_name='api_timwech_msisdn_1e5a07_idx',
        ),
        migrations.RenameIndex(
            model_name='timwesyncorderlog',
            new_name='api_timwesy_msisdn_e3a434_idx',
            old_name='api_timwesy_msisdn_9b1f3a_idx',
        ),
        migrations.RenameIndex(
            model_name='timwesyncorderlog',
            new_name='api_timwesy_event_t_2c8f6f_idx',
            old_name='api_timwesy_event_t_4c7e21_idx',
        ),
    ]
