# Generated by Django 4.2.26 on 2026-09-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0103_rename_api_timwech_status_6d2b84_idx_api_timwech_status_093182_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['category', '-created_at'], name='api_reel_categor_f98341_idx'),
        ),
    ]
