# Generated by Django 4.2.26 on 2026-09-02 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0104_reel_category_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='original_image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='original_media',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='processing_failed',
            field=models.BooleanField(default=False),
        ),
    ]
