# Generated by Django 4.2.26 on 2026-09-06 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0105_reel_media_originals'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='image_medium',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='image_small',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='media_360',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='media_480',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
