# Generated by Django 4.2.26 on 2026-09-06 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0106_reel_media_variants'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='shared_reel',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='shares_in_messages',
                to='api.reel',
            ),
        ),
        migrations.AlterField(
            model_name='message',
            name='media_type',
            field=models.CharField(
                choices=[
                    ('text', 'Text'),
                    ('image', 'Image'),
                    ('video', 'Video'),
                    ('audio', 'Audio / Voice'),
                    ('file', 'File'),
                    ('post', 'Shared post'),
                ],
                default='text',
                max_length=16,
            ),
        ),
    ]
