# Generated by Django 4.2.26 on 2026-09-06 20:17

from decimal import Decimal

from django.db import migrations, models

# Rows created before this migration still hold the old shipped defaults, and
# AlterField only changes what NEW rows start from -- so without this every
# existing campaign would keep scoring shares at 3 and gifts at 5 while the
# code, the tests and the documentation all said 5 and 10.
#
# Only rows still sitting on the exact old defaults are moved. A campaign whose
# admin deliberately set some other number is left alone: this migration cannot
# tell "never touched" from "set to 3 on purpose", so it changes only the
# values it shipped and treats anything else as intentional.
OLD_SHARES, NEW_SHARES = Decimal('3.00'), Decimal('5.00')
OLD_GIFTS, NEW_GIFTS = Decimal('5.00'), Decimal('10.00')

SHARE_FIELDS = (
    'daily_shares_weight',
    'weekly_shares_weight',
    'monthly_shares_weight',
    'grand_qualification_shares_weight',
)
GIFT_FIELDS = (
    'daily_gifts_weight',
    'weekly_gifts_weight',
    'monthly_gifts_weight',
    'grand_qualification_gifts_weight',
)


def adopt_new_weights(apps, schema_editor):
    Config = apps.get_model('api', 'CampaignScoringConfig')
    for field in SHARE_FIELDS:
        Config.objects.filter(**{field: OLD_SHARES}).update(**{field: NEW_SHARES})
    for field in GIFT_FIELDS:
        Config.objects.filter(**{field: OLD_GIFTS}).update(**{field: NEW_GIFTS})


def restore_old_weights(apps, schema_editor):
    Config = apps.get_model('api', 'CampaignScoringConfig')
    for field in SHARE_FIELDS:
        Config.objects.filter(**{field: NEW_SHARES}).update(**{field: OLD_SHARES})
    for field in GIFT_FIELDS:
        Config.objects.filter(**{field: NEW_GIFTS}).update(**{field: OLD_GIFTS})


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0107_message_shared_reel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='daily_gifts_weight',
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text='Points per unique gifter on a post (Daily)',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='daily_shares_weight',
            field=models.DecimalField(
                decimal_places=2, default=5.0, help_text='Points per share (Daily)', max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='grand_qualification_gifts_weight',
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text='Points per unique gifter on a post (Qualification)',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='grand_qualification_shares_weight',
            field=models.DecimalField(
                decimal_places=2,
                default=5.0,
                help_text='Points per share (Qualification)',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='monthly_gifts_weight',
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text='Points per unique gifter on a post (Monthly)',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='monthly_shares_weight',
            field=models.DecimalField(
                decimal_places=2, default=5.0, help_text='Points per share (Monthly)', max_digits=5
            ),
        ),
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='weekly_gifts_weight',
            field=models.DecimalField(
                decimal_places=2,
                default=10.0,
                help_text='Points per unique gifter on a post (Weekly)',
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name='campaignscoringconfig',
            name='weekly_shares_weight',
            field=models.DecimalField(
                decimal_places=2, default=5.0, help_text='Points per share (Weekly)', max_digits=5
            ),
        ),
        migrations.RunPython(adopt_new_weights, restore_old_weights),
    ]
