# Generated by Django 4.2.26 on 2026-09-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0108_campaign_engagement_weights'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoinbalance',
            name='bonus_balance',
            field=models.PositiveIntegerField(
                default=0, help_text='Granted with a subscription. Cannot be gifted.'
            ),
        ),
        migrations.AddField(
            model_name='usercoinbalance',
            name='total_bonus_granted',
            field=models.PositiveIntegerField(
                default=0, help_text='Lifetime subscription bonus coins granted'
            ),
        ),
    ]
