# Generated by Django 4.2.26 on 2026-09-06 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0109_coin_bonus_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='bonus_coins_granted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subscriptiontier',
            name='bonus_coins',
            field=models.PositiveIntegerField(
                default=0,
                help_text='Bonus coins granted each time this tier activates or renews. These are tracked separately and cannot be used to send gifts.',
            ),
        ),
    ]
