# Generated by Django 4.2.26 on 2026-09-07 06:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0110_subscription_bonus_coins'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending Approval'),
                            ('active', 'Active'),
                            ('suspended', 'Suspended'),
                        ],
                        default='pending',
                        max_length=20,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='campaign',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='campaigns_approved',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='rejection_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='submitted_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='campaigns_submitted',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='realm',
            field=models.CharField(
                choices=[
                    ('FLIPSTAR', 'Flipstar'),
                    ('MEMBER', 'Member'),
                    ('ORGANIZATION', 'Organization'),
                ],
                db_index=True,
                default='MEMBER',
                help_text='What kind of account this is. Every user has exactly one.',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(
                blank=True,
                choices=[('MAKER', 'Maker'), ('CHECKER', 'Checker')],
                db_index=True,
                help_text='Optional responsibility (maker/checker) within the realm.',
                max_length=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(
                choices=[
                    ('draft', 'Draft'),
                    ('submitted', 'Submitted for Approval'),
                    ('approved', 'Approved'),
                    ('rejected', 'Rejected'),
                    ('active', 'Active'),
                    ('voting', 'Voting Phase'),
                    ('completed', 'Completed'),
                    ('cancelled', 'Cancelled'),
                ],
                default='draft',
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name='organization',
            name='created_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='organizations_created',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='campaign',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Owning organization. NULL means a platform (Flipstar) campaign.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='campaigns',
                to='api.organization',
            ),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='organization',
            field=models.ForeignKey(
                blank=True,
                help_text='Required when realm is ORGANIZATION; empty otherwise.',
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='members',
                to='api.organization',
            ),
        ),
        migrations.AddIndex(
            model_name='organization',
            index=models.Index(fields=['status'], name='api_organiz_status_462811_idx'),
        ),
        # Ordered last, deliberately. Django autodetected this constraint
        # BEFORE the userprofile.organization field it references, which
        # fails with FieldError on a fresh database. The constraint has to
        # follow every column it names.
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.CheckConstraint(
                check=models.Q(
                    models.Q(('organization__isnull', False), ('realm', 'ORGANIZATION')),
                    models.Q(
                        models.Q(('realm', 'ORGANIZATION'), _negated=True),
                        ('organization__isnull', True),
                    ),
                    _connector='OR',
                ),
                name='profile_organization_matches_realm',
            ),
        ),
    ]
