# Generated by Django 4.2.26 on 2026-09-07 16:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0112_organization_admin_role_and_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinConfiguration',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('like_reward', models.PositiveIntegerField(default=0)),
                ('comment_reward', models.PositiveIntegerField(default=0)),
                ('share_reward', models.PositiveIntegerField(default=0)),
                ('gift_reward', models.PositiveIntegerField(default=0)),
                (
                    'participation_reward',
                    models.PositiveIntegerField(
                        default=0, help_text='Coins for joining the campaign.'
                    ),
                ),
                (
                    'completion_reward',
                    models.PositiveIntegerField(
                        default=0, help_text='Coins for completing the campaign.'
                    ),
                ),
                (
                    'max_reward_per_user',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Total coins one user may earn from this campaign. 0 = no limit.',
                    ),
                ),
                (
                    'max_daily_reward_per_user',
                    models.PositiveIntegerField(
                        default=0, help_text='Coins one user may earn per day. 0 = no limit.'
                    ),
                ),
                (
                    'budget',
                    models.PositiveIntegerField(
                        default=0,
                        help_text='Total coins this campaign may distribute. 0 = no budget set.',
                    ),
                ),
                (
                    'distributed',
                    models.PositiveIntegerField(
                        default=0, help_text='Coins paid out so far. Maintained by the reward path.'
                    ),
                ),
                (
                    'rewards_enabled',
                    models.BooleanField(
                        default=False,
                        help_text='Off by default: enabling this starts minting coins on engagement.',
                    ),
                ),
                ('is_active', models.BooleanField(default=True)),
                (
                    'locked_at',
                    models.DateTimeField(
                        blank=True,
                        help_text='When this configuration was frozen for a live campaign.',
                        null=True,
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'campaign',
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coin_configuration',
                        to='api.campaign',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coin_configurations',
                        to='api.organization',
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='max_comment_reward',
            field=models.PositiveIntegerField(
                default=20, help_text='Most coins an organization may pay per comment.'
            ),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='max_gift_reward',
            field=models.PositiveIntegerField(
                default=100, help_text='Most coins an organization may pay per gift.'
            ),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='max_like_reward',
            field=models.PositiveIntegerField(
                default=10, help_text='Most coins an organization may pay per like.'
            ),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='max_share_reward',
            field=models.PositiveIntegerField(
                default=50, help_text='Most coins an organization may pay per share.'
            ),
        ),
        migrations.CreateModel(
            name='CampaignRewardGrant',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('action', models.CharField(max_length=32)),
                (
                    'reference',
                    models.CharField(
                        help_text='What earned it: reel id, comment id, gift transaction id.',
                        max_length=64,
                    ),
                ),
                (
                    'coins',
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(0)]
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'campaign',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='reward_grants',
                        to='api.campaign',
                    ),
                ),
                (
                    'configuration',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='grants',
                        to='api.coinconfiguration',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='campaign_reward_grants',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name='CoinConfigurationAudit',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name='ID'
                    ),
                ),
                ('field', models.CharField(max_length=64)),
                ('previous_value', models.CharField(max_length=64)),
                ('new_value', models.CharField(max_length=64)),
                ('reason', models.TextField(blank=True, default='')),
                ('changed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'campaign',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='coin_config_audits',
                        to='api.campaign',
                    ),
                ),
                (
                    'changed_by',
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='coin_config_changes',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    'configuration',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='audit_entries',
                        to='api.coinconfiguration',
                    ),
                ),
                (
                    'organization',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='coin_config_audits',
                        to='api.organization',
                    ),
                ),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [
                    models.Index(
                        fields=['organization', '-changed_at'],
                        name='api_coincon_organiz_789b26_idx',
                    ),
                    models.Index(
                        fields=['configuration', '-changed_at'],
                        name='api_coincon_configu_20f220_idx',
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='coinconfiguration',
            index=models.Index(
                fields=['organization', 'campaign'], name='api_coincon_organiz_58b36f_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='coinconfiguration',
            constraint=models.UniqueConstraint(
                condition=models.Q(('campaign__isnull', True)),
                fields=('organization',),
                name='one_default_coin_config_per_organization',
            ),
        ),
        migrations.AddConstraint(
            model_name='coinconfiguration',
            constraint=models.CheckConstraint(
                check=models.Q(
                    ('budget', 0), ('distributed__lte', models.F('budget')), _connector='OR'
                ),
                name='coin_config_distributed_within_budget',
            ),
        ),
        migrations.AddIndex(
            model_name='campaignrewardgrant',
            index=models.Index(fields=['campaign', 'user'], name='api_campaig_campaig_779daf_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignrewardgrant',
            index=models.Index(
                fields=['user', '-created_at'], name='api_campaig_user_id_5fa73f_idx'
            ),
        ),
        migrations.AddConstraint(
            model_name='campaignrewardgrant',
            constraint=models.UniqueConstraint(
                fields=('campaign', 'user', 'action', 'reference'), name='one_reward_per_engagement'
            ),
        ),
    ]
