# Generated by Django 4.2.26 on 2026-09-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0113_organization_coin_configuration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='payment_method',
            field=models.CharField(choices=[('onevas', 'Onevas Airtime'), ('timwe', 'TIMWE Airtime'), ('telebirr', 'Telebirr'), ('coins', 'Coins')], default='onevas', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='payment_method',
            field=models.CharField(choices=[('onevas', 'Onevas Airtime'), ('timwe', 'TIMWE Airtime'), ('telebirr', 'Telebirr'), ('coins', 'Coins')], default='onevas', max_length=20),
        ),
    ]
