# Generated by Django 4.2.26 on 2026-09-09 02:25

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0114_timwe_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmsMessage',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('idempotency_key', models.CharField(max_length=255, unique=True)),
                ('recipient', models.CharField(db_index=True, max_length=20)),
                ('body', models.TextField()),
                ('purpose', models.CharField(blank=True, default='', max_length=64)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('queued', 'Queued'),
                            ('submitted', 'Submitted to gateway'),
                            ('delivered', 'Delivered to handset'),
                            ('failed', 'Failed'),
                            ('rejected', 'Rejected by gateway'),
                            ('expired', 'Expired before delivery'),
                        ],
                        db_index=True,
                        default='queued',
                        max_length=20,
                    ),
                ),
                ('provider', models.CharField(blank=True, default='', max_length=32)),
                (
                    'provider_message_id',
                    models.CharField(blank=True, db_index=True, default='', max_length=128),
                ),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('error_code', models.CharField(blank=True, default='', max_length=64)),
                ('error_message', models.TextField(blank=True, default='')),
                ('raw_dlr', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(
                        fields=['status', 'created_at'], name='api_smsmess_status_7de531_idx'
                    )
                ],
            },
        ),
    ]
