# Generated by Django 4.2.26 on 2026-09-10 08:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0115_sms_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='timwechargetransaction',
            name='coin_package',
            field=models.ForeignKey(blank=True, help_text='What the charge paid for, when it was a coin purchase', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timwe_charge_transactions', to='api.coinpackage'),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='duration_ms',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='fulfilled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='http_status',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='outcome',
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
