# Generated by Django 4.2.26 on 2026-09-10 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0116_timwe_charge_lifecycle'),
    ]

    operations = [
        migrations.AddField(
            model_name='timwechargetransaction',
            name='product_id',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='purpose',
            field=models.CharField(blank=True, choices=[('coin_purchase', 'Coin purchase'), ('subscription_renewal', 'Subscription renewal'), ('manual_check', 'Manual check')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='renewal_period_end',
            field=models.DateTimeField(blank=True, help_text='The end_date the renewal charge was for', null=True),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='service_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='short_code',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='timwechargetransaction',
            name='subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='timwe_renewal_charges', to='api.subscriptionplan'),
        ),
        migrations.AddIndex(
            model_name='timwechargetransaction',
            index=models.Index(fields=['purpose', 'status'], name='api_timwech_purpose_b057b8_idx'),
        ),
        migrations.AddConstraint(
            model_name='timwechargetransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('purpose', 'subscription_renewal')), fields=('subscription', 'renewal_period_end'), name='timwe_one_renewal_charge_per_period'),
        ),
    ]
