# Generated by Django 4.2.26 on 2026-09-11 09:42
#
# Media pipeline state on Reel. Every existing row takes the READY default --
# each was published as-is and is served exactly as before -- except those the
# worker already gave up on, which become FAILED so the two flags and the new
# status agree from the start.

from django.db import migrations, models


def mark_failed_rows(apps, schema_editor):
    Reel = apps.get_model('api', 'Reel')
    Reel.objects.filter(processing_failed=True).update(processing_status='FAILED')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0117_timwe_subscription_renewal'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='client_upload_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reel',
            name='image_medium_webp',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='image_small_webp',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='image_webp',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='reel',
            name='long_video_charged',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='media_version',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reel',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='processed_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='processing_error',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AddField(
            model_name='reel',
            name='processing_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='processing_status',
            field=models.CharField(choices=[('UPLOADING', 'Uploading'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('FAILED', 'Failed')], default='READY', max_length=12),
        ),
        migrations.AddField(
            model_name='reel',
            name='processing_task_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='reel',
            name='source_deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reel',
            name='source_size',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='reel',
            index=models.Index(fields=['processing_status', '-created_at'], name='api_reel_process_0e7408_idx'),
        ),
        migrations.AddConstraint(
            model_name='reel',
            constraint=models.UniqueConstraint(condition=models.Q(('client_upload_id', ''), _negated=True), fields=('user', 'client_upload_id'), name='reel_one_post_per_client_upload'),
        ),
        migrations.RunPython(mark_failed_rows, migrations.RunPython.noop),
    ]
