# Generated by Django 4.2.26 on 2026-09-12 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0118_reel_media_pipeline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reel',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='reels/'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='media',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='reels/'),
        ),
        migrations.AlterField(
            model_name='reel',
            name='thumbnail',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='thumbnails/'),
        ),
    ]
