# Generated by Django 4.2.26 on 2026-09-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0119_reel_media_url_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='reel',
            name='processing_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
