# Generated by Django 4.2.26 on 2026-09-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0120_reel_processing_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timwesyncorderlog',
            name='order_key',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='timwesyncorderlog',
            name='transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
    ]
