# Generated by Django 4.2.26 on 2026-09-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0121_widen_timwe_sync_order_identifiers'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='timwechargetransaction',
            name='timwe_one_renewal_charge_per_period',
        ),
        migrations.AddConstraint(
            model_name='timwechargetransaction',
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ('purpose', 'subscription_renewal'),
                    models.Q(('status', 'failed'), _negated=True),
                ),
                fields=('subscription', 'renewal_period_end'),
                name='timwe_one_live_renewal_charge_per_period',
            ),
        ),
    ]
