# Generated by Django 4.2.26 on 2026-09-19 17:02

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0123_subscription_charge_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='cointransaction',
            name='amount_etb',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Birr charged for a custom-amount purchase (packages carry their own price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='cointransaction',
            name='quoted_coins',
            field=models.PositiveIntegerField(blank=True, help_text='Coins the server committed to for a custom-amount purchase', null=True),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='custom_purchase_max_etb',
            field=models.DecimalField(decimal_places=2, default=Decimal('1000.00'), help_text='Largest custom coin purchase, in ETB', max_digits=10),
        ),
        migrations.AddField(
            model_name='walletconfig',
            name='custom_purchase_min_etb',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Smallest custom coin purchase, in ETB', max_digits=10),
        ),
    ]
