# Generated by Django 4.2.26 on 2026-09-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0124_custom_coin_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cointransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Coin Purchase'), ('welcome_bonus', 'Welcome Bonus'), ('daily_login', 'Daily Login Bonus'), ('subscription_gift', 'Subscription Charge Gift'), ('ondemand_allocation', 'On-Demand Coin Allocation'), ('spin_reward', 'Daily Spin Reward'), ('post_bonus', 'Daily Post Bonus'), ('campaign_join', 'Campaign Join Reward'), ('campaign_winner', 'Campaign Winner Reward'), ('like_received', 'Like Received'), ('comment_reward', 'Quality Comment Reward'), ('referral', 'Referral Bonus'), ('profile_complete', 'Profile Completion'), ('gift_sent', 'Gift Sent'), ('gift_received', 'Gift Received'), ('boost', 'Post Boost'), ('extra_entry', 'Extra Entry'), ('campaign_like', 'Campaign Like Cost'), ('campaign_comment', 'Campaign Comment Cost'), ('campaign_share', 'Campaign Share Cost'), ('campaign_gift_fee', 'Campaign Gift Fee'), ('reward', 'Generic Reward'), ('refund', 'Refund'), ('withdrawal', 'Withdrawal to Birr'), ('admin_adjustment', 'Admin Adjustment')], max_length=20),
        ),
        migrations.AddConstraint(
            model_name='cointransaction',
            constraint=models.UniqueConstraint(condition=models.Q(('transaction_type', 'ondemand_allocation')), fields=('transaction_type', 'payment_reference'), name='one_ondemand_allocation_per_payment'),
        ),
    ]
