# Generated by Django 4.2.26 on 2026-09-22 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0130_post_creation_coin_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_post_create',
            field=models.PositiveIntegerField(
                default=2, help_text='Cost to create a post (0 = free)'
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_post_create_long_video',
            field=models.PositiveIntegerField(
                default=98,
                help_text='Additional coins for campaign videos of 60 seconds or longer (0 = free). Added to cost_post_create, so 2 + 98 = 100 for a long video.',
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_post_create_long_video_non_campaign',
            field=models.PositiveIntegerField(
                default=98,
                help_text='Additional coins for non-campaign videos of 60 seconds or longer (0 = free). Added to cost_post_create_non_campaign, so 2 + 98 = 100 for a long video.',
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_post_create_non_campaign',
            field=models.PositiveIntegerField(
                default=2, help_text='Cost to create a non-campaign post (0 = free)'
            ),
        ),
    ]
