# Generated by Django 4.2.26 on 2026-09-23 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0131_post_creation_coin_cost_defaults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='currency',
            field=models.CharField(default='ETB', max_length=10),
        ),
        migrations.AlterField(
            model_name='timwechargetransaction',
            name='currency',
            field=models.CharField(max_length=10),
        ),
    ]
