# Generated by Django 4.2.26 on 2026-09-23 17:34

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0132_widen_currency_for_timwe_spelling'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentVerificationSession',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ('phone_number', models.CharField(db_index=True, max_length=20)),
                (
                    'purpose',
                    models.CharField(
                        choices=[
                            ('coin_purchase', 'Coin purchase'),
                            ('subscription', 'Subscription'),
                        ],
                        max_length=20,
                    ),
                ),
                ('request_fingerprint', models.CharField(max_length=64)),
                ('otp_hash', models.CharField(max_length=255)),
                ('otp_expires_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('send_count', models.PositiveSmallIntegerField(default=0)),
                ('last_sent_at', models.DateTimeField(blank=True, null=True)),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('pending', 'Pending'),
                            ('verified', 'Verified'),
                            ('consumed', 'Consumed'),
                            ('blocked', 'Blocked'),
                        ],
                        default='pending',
                        max_length=12,
                    ),
                ),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('session_expires_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    'user',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='payment_verification_sessions',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'payment verification session',
                'indexes': [
                    models.Index(
                        fields=['phone_number', 'status'], name='api_payment_phone_n_72ed8e_idx'
                    ),
                    models.Index(
                        fields=['status', 'created_at'], name='api_payment_status_6b9b98_idx'
                    ),
                ],
            },
        ),
    ]
