# Generated by Django 4.2.26 on 2026-09-23 19:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0133_payment_verification_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentverificationsession',
            name='purpose',
            field=models.CharField(choices=[('subscription', 'Subscription')], max_length=20),
        ),
    ]
