"""Engagement costs: like 1, comment 2, share 5.

These defaulted to 0, so liking, commenting and sharing were free. The
charging machinery was already in place and correct
(api/services/campaign_charges.py) -- it simply had nothing to charge, because
``engagement_cost`` returns 0 and ``charge_engagement`` returns early.

AlterField alone would fix only rows created from here on. WalletConfig is a
singleton-ish runtime row that already exists in every environment, so it
needs the data step too.

Only a row still holding 0 is changed, so a price somebody has deliberately
set in the admin -- including a deliberate 0, to run a free period -- is not
overwritten by a deploy. That is the same rule migrations 0128 and 0135 use
for the subscription gift amounts.
"""

# Generated by Django 4.2.26 on 2026-09-25 05:35

from django.db import migrations, models

#: field -> the price the business requirement sets.
COSTS = {
    'cost_like': 1,
    'cost_comment': 2,
    'cost_share': 5,
    'cost_like_non_campaign': 1,
    'cost_comment_non_campaign': 2,
    'cost_share_non_campaign': 5,
}

#: What they held while engagement was free. Only these are changed.
WAS_FREE = 0


def set_costs(apps, schema_editor):
    WalletConfig = apps.get_model('api', 'WalletConfig')
    for field, price in COSTS.items():
        WalletConfig.objects.filter(**{field: WAS_FREE}).update(**{field: price})


def unset_costs(apps, schema_editor):
    WalletConfig = apps.get_model('api', 'WalletConfig')
    for field, price in COSTS.items():
        WalletConfig.objects.filter(**{field: price}).update(**{field: WAS_FREE})


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0135_weekly_gift_twenty_three'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_comment',
            field=models.PositiveIntegerField(
                default=2, help_text='Coins charged when commenting on a campaign post (0 = free)'
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_comment_non_campaign',
            field=models.PositiveIntegerField(
                default=2,
                help_text='Coins charged when commenting on a non-campaign post (0 = free)',
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_like',
            field=models.PositiveIntegerField(
                default=1, help_text='Coins charged when liking a campaign post (0 = free)'
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_like_non_campaign',
            field=models.PositiveIntegerField(
                default=1, help_text='Coins charged when liking a non-campaign post (0 = free)'
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_share',
            field=models.PositiveIntegerField(
                default=5, help_text='Coins charged when sharing a campaign post (0 = free)'
            ),
        ),
        migrations.AlterField(
            model_name='walletconfig',
            name='cost_share_non_campaign',
            field=models.PositiveIntegerField(
                default=5, help_text='Coins charged when sharing a non-campaign post (0 = free)'
            ),
        ),
        migrations.RunPython(set_costs, unset_costs),
    ]
