# Generated by Django 4.2.26 on 2026-09-25 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0137_prize_delivery_tracking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='winner_count',
            field=models.IntegerField(default=1, help_text='Number of winners. Ignored for the four standard tiers -- Daily Sprint pays 20, Weekly Battle 10, Monthly Star 5 and the Grand Final 1, from api/services/prize_structure.py, because those counts are advertised and not an admin setting. Used only by a campaign whose type is not one of those.'),
        ),
    ]
