# Generated by Django 4.2.26 on 2026-09-25 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0138_winner_count_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='boostcampaign',
            name='boost_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium'), ('viral', 'Viral'), ('custom', 'Custom (hourly)')], default='custom', max_length=20),
        ),
        migrations.AddField(
            model_name='boostcampaign',
            name='guaranteed_impressions',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='boostcampaign',
            name='placement',
            field=models.CharField(choices=[('trending', 'Top of Trending'), ('feed', 'Top of the feed'), ('everywhere', 'Trending and the feed')], default='trending', max_length=20),
        ),
    ]
