# Generated by Django 4.2.26 on 2026-09-25 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0139_boost_tiers'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='boostcampaign',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), models.Q(('boost_type', 'custom'), _negated=True)), fields=('reel',), name='one_active_tier_boost_per_reel'),
        ),
    ]
