# Generated by Django 4.2.26 on 2026-09-25 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0140_one_active_tier_boost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boostcampaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('exhausted', 'Budget Exhausted'), ('undelivered', 'Ended Below Guarantee')], default='active', max_length=20),
        ),
    ]
