# Generated by Django 4.2.26 on 2026-09-25 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0141_boost_undelivered_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationpreference',
            name='gifts',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='system',
            field=models.BooleanField(default=True, help_text='Subscription, prize and withdrawal notices about your own account.'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('follow', 'Follow'), ('mention', 'Mention'), ('gift', 'Gift'), ('moderation', 'Moderation Action'), ('subscription_activated', 'Subscription Activated'), ('subscription_renewed', 'Subscription Renewed'), ('subscription_expired', 'Subscription Expired'), ('prize_won', 'Prize Won'), ('prize_delivered', 'Prize Delivered'), ('withdrawal_paid', 'Withdrawal Paid')], max_length=32),
        ),
        migrations.AlterField(
            model_name='notification',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='PointTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('gift_received', 'Gift Received'), ('campaign_reward', 'Campaign Reward'), ('withdrawal', 'Withdrawal to Birr'), ('withdrawal_refund', 'Withdrawal Refund'), ('swap', 'Swapped to Coins'), ('expiry', 'Expired After Inactivity'), ('admin_adjustment', 'Admin Adjustment')], max_length=32)),
                ('points', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='api_pointtr_user_id_b71825_idx'), models.Index(fields=['transaction_type', '-created_at'], name='api_pointtr_transac_9148c5_idx')],
            },
        ),
    ]
