# Generated by Django 4.2.26 on 2026-09-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0144_h04_unique_originator_conversation_id'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cointransaction',
            index=models.Index(fields=['user', '-created_at'], name='cointx_user_created_idx'),
        ),
    ]
