apiVersion: v1
kind: ServiceAccount
metadata:
  name: flipstar-backend
  labels:
    app.kubernetes.io/name: flipstar-backend
    app.kubernetes.io/part-of: flipstar
automountServiceAccountToken: false
