apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: flipstar-backend
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    acme.cert-manager.io/http01-ingress-class: nginx
    acme.cert-manager.io/http01-edit-in-place: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - api.uat.flipstar.et
      secretName: flipstar-staging-tls

  rules:
    - host: api.uat.flipstar.et
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flipstar-backend
                port:
                  name: http
