apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: flipstar-backend
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "100m"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - api.uat.flipstar.et
        - uat.flipstar.et
        - flipstar.et
      secretName: flipstar-staging-tls

  rules:
    - host: api.uat.flipstar.et
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flipstar-backend
                port:
                  name: http
    - host: uat.flipstar.et
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flipstar-backend
                port:
                  name: http
    - host: flipstar.et
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: flipstar-backend
                port:
                  name: http
